services:
  server:
    working_dir: /app
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./alembic:/app/alembic
      - ./core:/app/core
      - ./htmlcov:/app/htmlcov
    depends_on:
      - postgres
    restart: on-failure


  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # Admin user and main DB
      POSTGRES_USER: ${DATABASE_ADMIN_USER}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      # User for application
      APP_USER: ${DATABASE_USER}
      APP_USER_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/create-app-user.sh:/docker-entrypoint-initdb.d/create-app-user.sh
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - pg_admin_data:/var/lib/pg_admin/data
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pg_admin_data:
    driver: local